workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: $CI_COMMIT_TAG

cache:
  key: uv
  paths:
    - .cache/uv

variables:
  PYTHONUNBUFFERED: "1"
  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/.cache"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

default:
  tags:
    - docker
  image: python:3.12

stages:
  - qa
  - test

quality:
  stage: qa
  before_script:
    - pip install uv
    - uv sync --extra dev
  script:
    - uv run reuse lint
    - uv run pre-commit run --all-files --show-diff-on-failure --verbose
  needs: []
  cache:
    key: pre-commit-cache
    paths:
      - .cache/pip
      - .cache/pre-commit
      - .cache/uv
  rules:
    - exists:
      - .pre-commit-config.yaml

tests:
  stage: test
  needs:
    - job: quality
      optional: true
  before_script:
    - apt update && apt install -y libegl1 libgles2 libsm6 libxext6 ffmpeg libfontconfig1 libxrender1
    - pip install uv
    - uv sync --extra dev
  script:
    - uv run pytest -sv --cov-report "html:html/coverage" --cov-report "xml:coverage.xml" --junitxml "junit-coverage.xml" --ignore ".profile"
  coverage: '/(?:TOTAL|total|Total).*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  cache:
    key: test-cache-${TAG}
    paths:
      - .cache/uv
  artifacts:
    paths:
      - html
    reports:
      junit: junit-coverage.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
